language: python
cache: pip
sudo: false

# FIXME - ideally need to test on python 2
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.7-dev"

install:
  - pip install 'requests>=2.7'
  - pip install coveralls
  - pip install vcrpy
  - pip install mypy mypy-extensions

script:
  - nosetests -v --cover-package=habanero
  - mypy habanero

after_success:
  - coveralls --verbose
